Fix compiler warnings under Fedora 31
When compiling with GCC Red Hat 9.2.1-1 under Fedora 31, the following
warnings were shown

functions.c: In function ‘DBInit’:
functions.c:320:28: warning: implicit declaration of function ‘malloc’ [-Wimplicit-function-declaration]
  320 |    if (!(db = (DATABASE *) malloc (sizeof (DATABASE)))) {
      |                            ^~~~~~
functions.c:320:28: warning: incompatible implicit declaration of built-in function ‘malloc’
functions.c:21:1: note: include ‘<stdlib.h>’ or provide a declaration of ‘mallo’
   20 | #include "globals.h"
  +++ |+#include <stdlib.h>
   21 |
functions.c: In function ‘DBFinish’:
functions.c:365:32: warning: ‘calloc’ argument 1 type is ‘int’ where ‘long unsigned int’ is expected in a call to built-in function declared without prototype -Wbuiltin-declaration-mismatch]
  365 |   (XSegment *) calloc (database->linecount, sizeof (XSegment)))) {
      |                        ~~~~~~~~^~~~~~~~~~~
functions.c:362:10: note: built-in ‘calloc’ declared here
  362 |    void *calloc ();
      |          ^~~~~~
functions.c: In function ‘DBAlloc’:
functions.c:407:37: warning: incompatible implicit declaration of built-in function ‘malloc’
  407 |    if (!(entry = (struct dbentry *) malloc (sizeof (struct dbentry)))) {
      |                                     ^~~~~~
functions.c:407:37: note: include ‘<stdlib.h>’ or provide a declaration of ‘malloc’

So #include stdlib.h in functions.c. This is included after the local
includes so that we get the _DEFAULT_SOURCE define from xlander.h.

Also remove the cast of the return from malloc(3) as that's not required
(and indeed can hide bugs) in C.

Finally remove the declaration of calloc(3), that's declared in
stdlib.h.

Signed-off-by: Andrew Clayton <andrew@digital-domain.net>